### ISSUE TITLE
Problem while parsing the package

### ISSUE THREAD

**Issue by vayloz** [qwerttyuiiop1/Arknights-Autoclicker#1]
Unable to install, pop message: "There was problem while parsing the package."
Model: Redmi 8
Android Version: 10
Steps to reproduce the issue:
1. Attempt to install
![unable_to_install](https://github.com/qwerttyuiiop1/Arknights-Autoclicker/assets/36890581/737c24bf-b908-455f-a13a-80eeab5fe328)

**Comment by qwerttyuiiop1** [comment]
Seems to be an issue with the api level, I changed it to api 28 (Android 9), please see 
[Test changes](https://github.com/qwerttyuiiop1/Arknights-Autoclicker/releases/tag/v0.0.1-test)


Also haven't tested how the arknights UI would change on different resolutions, I'll try to get back to this issue and test it in around 2 or 1 week.

EDIT: nvm I'll be quite busy until december break
